# Generated by Django 4.2.3 on 2023-12-01 18:32

from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        error_messages={
                            "title": ["este campo não pode estar vazio"]
                        },
                        max_length=200,
                        validators=[news.models.validate_title],
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        error_messages={
                            "content": ["este campo não pode estar vazio"]
                        }
                    ),
                ),
                ("created_at", models.DateField()),
                ("image", models.ImageField(blank=True, upload_to="")),
                (
                    "author",
                    models.ForeignKey(
                        max_length=200,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news.user",
                    ),
                ),
                ("categories", models.ManyToManyField(to="news.category")),
            ],
        ),
    ]
